{{- if .Values.placement.multicluster.enabled }}
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: modresortapp101-modresortapp
  namespace: modresort-project
  labels:
    app: modresortapp
    chart: modresortapp-0.1.0
    release: modresort101
    heritage: Tiller
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:  
      environment: Dev
{{- end }}

